# Site settings
title: Abhishek Venkatakrishna
description: Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Hi, I'm Abhishek Vennkatakrishna
user_description: Freindly Neighbourhood Coding Wizard ! 😊
user_title: I'm Backend Developer/Automation Engineer
email: vabhishek6@gmail.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
